// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cduqnvrloivfzuflhbim.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkdXFudnJsb2l2Znp1ZmxoYmltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwNDUzMTAsImV4cCI6MjA1NDYyMTMxMH0.He9xx70oXAetUGTFZpO3ZuYlBV9rNpa4C4gaXtNt1MQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);